version: "3.3"

services:

  monitor:
    image: vfarcic/docker-flow-monitor:${TAG:-2-18.01.14-44}
    ports:
      - 8082:8080
    volumes:
      - monitor2:/prometheus
    environment:
      - GLOBAL_SCRAPE_INTERVAL=1m
      - ARG_WEB_EXTERNAL-URL=http://${MONITOR_DOMAIN:-localhost}
      - ARG_ALERTMANAGER_URL=http://alertmanager:9093
      - ARG_STORAGE_LOCAL_RETENTION=168h
    networks:
      - proxy
      - monitor
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=${MONITOR_DOMAIN}
        - com.df.port=9090
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.9
        - com.df.alertFor=30s
        - com.df.scrapePort=9090
        - com.df.usersPassEncrypted=true
        - com.df.usersSecret=admin
      placement:
        constraints:
          - node.role == worker
      resources:
        reservations:
          memory: 7G
        limits:
          memory: 7G

  alertmanager:
    image: prom/alertmanager
    networks:
      - monitor
    secrets:
      - alertmanager_config
    deploy:
      labels:
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      placement:
        constraints:
          - node.role == worker
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
    command: -config.file=/run/secrets/alertmanager_config -storage.path=/alertmanager

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:${DFMSL_TAG:-18.01.06-29}
    networks:
      - monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/remove
    deploy:
      resources:
        reservations:
          memory: 16M
        limits:
          memory: 32M
      placement:
        constraints: 
          - node.role == manager

volumes:

  monitor2:
    driver: cloudstor:aws
    driver_opts:
      ebstype: gp2
      size: 500
      backing: relocatable
    external: false

networks:

  monitor:
    external: true

  proxy:
    external: true


secrets:

  alertmanager_config:
    external: true